
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import sun.security.krb5.SCDynamicStoreConfig;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dsd09
 */
public class Cafe extends javax.swing.JFrame {

    /**
     * Creates new form Cafe
     */
    //global variables
    private boolean appendToFile; // true: yes, false : no,

    public Cafe() {
        initComponents();// initComponents ALWAYS first

        //first element on the list to be set as a default
        cmbMealType.setSelectedItem(0);

        //select the append to file radio button
        //rbAppendToFile.doClick();
        rbTea.setActionCommand("tea");
        rbCoffee.setActionCommand("coffee");
        rbCoke.setActionCommand("coke");
        rbOrange.setActionCommand("orange");
        rbWater.setActionCommand("water");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupExtras = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbCafe = new javax.swing.JLabel();
        lbImage = new javax.swing.JLabel();
        lbMealType = new javax.swing.JLabel();
        lbOptions = new javax.swing.JLabel();
        lbDrink = new javax.swing.JLabel();
        lbExtras = new javax.swing.JLabel();
        rbTea = new javax.swing.JRadioButton();
        rbCoffee = new javax.swing.JRadioButton();
        rbCoke = new javax.swing.JRadioButton();
        rbWater = new javax.swing.JRadioButton();
        rbOrange = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnPlaceOrder = new javax.swing.JButton();
        cmbMealType = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOptions = new javax.swing.JList();
        btnSaveToFile = new javax.swing.JButton();
        btnLoadFromFile = new javax.swing.JButton();
        btnResetForm = new javax.swing.JButton();
        plnExtras = new javax.swing.JPanel();
        cbButter = new javax.swing.JCheckBox();
        cbVinegar = new javax.swing.JCheckBox();
        cbKetchup = new javax.swing.JCheckBox();
        cbMayo = new javax.swing.JCheckBox();
        plnFileEditMode = new javax.swing.JPanel();
        rbOverwrite = new javax.swing.JRadioButton();
        bdAppendFile = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCafe.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        lbCafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCafe.setText("Agnes's Cafe");
        lbCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast.jpg"))); // NOI18N
        lbImage.setText("jLabel2");

        lbMealType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMealType.setText("Meal Type");

        lbOptions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbOptions.setText("Options");

        lbDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDrink.setText("Drink");

        lbExtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbExtras.setText("Extras");

        buttonGroup1.add(rbTea);
        rbTea.setText("Tea");

        buttonGroup1.add(rbCoffee);
        rbCoffee.setText("Coffee");

        buttonGroup1.add(rbCoke);
        rbCoke.setText("Coke");

        buttonGroup1.add(rbWater);
        rbWater.setText("Water");

        buttonGroup1.add(rbOrange);
        rbOrange.setText("Orange");

        txtArea.setColumns(20);
        txtArea.setLineWrap(true);
        txtArea.setRows(5);
        txtArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtArea);

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        cmbMealType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Breakfast", "Lunch", "Dinner" }));
        cmbMealType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMealTypeActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstOptions);

        btnSaveToFile.setText("Save to File");
        btnSaveToFile.setEnabled(false);
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        btnLoadFromFile.setText("Load from File");
        btnLoadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromFileActionPerformed(evt);
            }
        });

        btnResetForm.setText("Reset Form");

        buttonGroupExtras.add(cbButter);
        cbButter.setText("Butter");

        buttonGroupExtras.add(cbVinegar);
        cbVinegar.setText("Vinegar");

        buttonGroupExtras.add(cbKetchup);
        cbKetchup.setText("Ketchup");

        buttonGroupExtras.add(cbMayo);
        cbMayo.setText("Mayo");

        javax.swing.GroupLayout plnExtrasLayout = new javax.swing.GroupLayout(plnExtras);
        plnExtras.setLayout(plnExtrasLayout);
        plnExtrasLayout.setHorizontalGroup(
            plnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVinegar)
                    .addComponent(cbKetchup)
                    .addComponent(cbMayo)
                    .addComponent(cbButter))
                .addContainerGap())
        );
        plnExtrasLayout.setVerticalGroup(
            plnExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbButter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMayo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbKetchup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVinegar)
                .addContainerGap())
        );

        plnFileEditMode.setBorder(javax.swing.BorderFactory.createTitledBorder("File Edit Mode"));

        buttonGroupExtras.add(rbOverwrite);
        rbOverwrite.setText("Overwrite");
        rbOverwrite.setBorder(new javax.swing.border.MatteBorder(null));

        buttonGroupExtras.add(bdAppendFile);
        bdAppendFile.setText("Append To File");
        bdAppendFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout plnFileEditModeLayout = new javax.swing.GroupLayout(plnFileEditMode);
        plnFileEditMode.setLayout(plnFileEditModeLayout);
        plnFileEditModeLayout.setHorizontalGroup(
            plnFileEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnFileEditModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plnFileEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdAppendFile)
                    .addComponent(rbOverwrite))
                .addGap(11, 11, 11))
        );
        plnFileEditModeLayout.setVerticalGroup(
            plnFileEditModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnFileEditModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bdAppendFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOverwrite)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(lbCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMealType)
                                    .addComponent(cmbMealType, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbOptions)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbOrange)
                                    .addComponent(lbDrink)
                                    .addComponent(rbTea)
                                    .addComponent(rbCoffee)
                                    .addComponent(rbCoke)
                                    .addComponent(rbWater))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plnExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbExtras)
                                        .addGap(11, 11, 11))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSaveToFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoadFromFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plnFileEditMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDrink)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbTea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCoffee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCoke)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbWater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbOrange))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbExtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plnExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plnFileEditMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLoadFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMealType)
                            .addComponent(lbOptions, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMealType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed

        //enable the FaveToFile button when an order has been placed
        btnSaveToFile.setEnabled(true);

        //order...
        String order = "";
        //get the options selected from the list
        String options = lstOptions.getSelectedValuesList().toString().toLowerCase();

        // adding menu's options list but without [ ]
        order += options.substring(1, options.length() - 1);

        ButtonModel model = buttonGroup1.getSelection();
        if (model != null) {
            order += ", ";
            order += model.getActionCommand();
        }

        /*  OR .... 
        
         if(rbCoffee.isSelected())
         order+= "coffee";
         else if (rbCoke.isSelected())
         order+="coke";
         else if (rbOrange.isSelected())
         order+="orange";
         else if (rbTea.isSelected())
         order+="tea";
         else
         order+="water";
        
   
         if(cbButter.isSelected())
         order+=" and butter";
         if(cbKetchup.isSelected())
         order+=" and ketchup";
         if(cbMayo.isSelected())
         order+=" and mayo";
         if(cbVinegar.isSelected())
         order+=" and vinegar";
         order+=".";
    
         txtArea.setText(order);
         */
        Component[] allCheckBoxes = plnExtras.getComponents();
        /* Loop through all components in that panel */
        for (Component c : allCheckBoxes) {
            // Cast c down from a Component to a JCheckBox so
            // I can call Checkbox methods 
            JCheckBox cb = ((JCheckBox) c);
            if (cb.isSelected()) { // If the checkbox is checked
                // Get its text and add it onto the order
                order += " and " + cb.getText().toLowerCase();
            }
        }
        // If the order String is empty show a message
        if (order.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please choose something");
        } else {
            txtArea.setText("You ordered " + order + ".");
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void cmbMealTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMealTypeActionPerformed
        //get the string selected in the comboBox
        String mealSelected = cmbMealType.getSelectedItem().toString();

        DefaultListModel<String> model = new DefaultListModel<>();

        //if its brakfast add breakfast menu to the list
        //if its lunch add lunch menu
        switch (mealSelected) {
            case "Breakfast":
                model.addElement("Sausages");
                model.addElement("Bacon");
                model.addElement("Onions");
                model.addElement("Mushrooms");
                model.addElement("Hashbrown");
                model.addElement("Beans");
                model.addElement("Toast");
                model.addElement("Fried Egg");
                model.addElement("Poached Egg");
                model.addElement("Scrambled Egg");
                break;
            case "Lunch":
                model.addElement("Sandwich");
                model.addElement("Soup");
                model.addElement("Chips");
                model.addElement("Salad");
                model.addElement("Crisps");
                model.addElement("Wrap");
                break;
            case "Dinner":
                model.addElement("Mashed Potatoe");
                model.addElement("Braised Steak");
                model.addElement("Chicken Wrap");
                model.addElement("Chips");
                model.addElement("Vegetables");
                model.addElement("Gravy");
                break;
            default:
                model.addElement("Choose Meal Type");
        }
        lstOptions.setModel(model); // loads the model into the option lists

    }//GEN-LAST:event_cmbMealTypeActionPerformed

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
        // make sure there is text int the tezt Area
        if (txtArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please place an order.");
        } else {  // write the order out to file
            //overwrite every time
            try (FileWriter fw = new FileWriter(new File("order.txt"), true);
                    PrintWriter pw = new PrintWriter(fw)) {
                pw.println(txtArea.getText());
                JOptionPane.showMessageDialog(this, "Order written to file");
            } catch (FileNotFoundException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Unable to create a file");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Unable to create a file");
            }
        }
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void btnLoadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromFileActionPerformed
        try (FileReader fr = new FileReader("order.txt");
                BufferedReader br = new BufferedReader(fr)) {

            String line = "";
            String wholeFile = "";

            while ((line = br.readLine()) != null) {
                wholeFile += line + "\n";
            }
            //add the whole file to the textArea
            if (wholeFile.isEmpty()) {
                JOptionPane.showMessageDialog(this, "File is empty");
            } else {
                txtArea.setText(wholeFile);
            }

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "File could not be opened");
        }
    }//GEN-LAST:event_btnLoadFromFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bdAppendFile;
    private javax.swing.JButton btnLoadFromFile;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupExtras;
    private javax.swing.JCheckBox cbButter;
    private javax.swing.JCheckBox cbKetchup;
    private javax.swing.JCheckBox cbMayo;
    private javax.swing.JCheckBox cbVinegar;
    private javax.swing.JComboBox cmbMealType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCafe;
    private javax.swing.JLabel lbDrink;
    private javax.swing.JLabel lbExtras;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbMealType;
    private javax.swing.JLabel lbOptions;
    private javax.swing.JList lstOptions;
    private javax.swing.JPanel plnExtras;
    private javax.swing.JPanel plnFileEditMode;
    private javax.swing.JRadioButton rbCoffee;
    private javax.swing.JRadioButton rbCoke;
    private javax.swing.JRadioButton rbOrange;
    private javax.swing.JRadioButton rbOverwrite;
    private javax.swing.JRadioButton rbTea;
    private javax.swing.JRadioButton rbWater;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
