
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dsd09
 */
public class CaHire extends javax.swing.JFrame {

    /**
     * Creates new form CaHire
     */
    public CaHire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTransmission = new javax.swing.ButtonGroup();
        buttonGroupFuelType = new javax.swing.ButtonGroup();
        buttonGroupNumberOfSeats = new javax.swing.ButtonGroup();
        lbImage = new javax.swing.JLabel();
        lbTheBestCarHire = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColour = new javax.swing.JLabel();
        lblFuelType = new javax.swing.JLabel();
        lblNumberOfSeats = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMake = new javax.swing.JList();
        lblTransmission = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rdAnyTransmission = new javax.swing.JRadioButton();
        rdManual = new javax.swing.JRadioButton();
        rdAutomatic = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        rdAnyFuelType = new javax.swing.JRadioButton();
        rdPetrol = new javax.swing.JRadioButton();
        rdDiesel = new javax.swing.JRadioButton();
        rdBioethanol = new javax.swing.JRadioButton();
        rdHybrid = new javax.swing.JRadioButton();
        rd7seats = new javax.swing.JRadioButton();
        rd2seats = new javax.swing.JRadioButton();
        rd4seats = new javax.swing.JRadioButton();
        rd5seats = new javax.swing.JRadioButton();
        rd8seats = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmbModel = new javax.swing.JComboBox();
        lbTheBestCarHire2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Hire Form");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car.jpg"))); // NOI18N
        lbImage.setText("Image");

        lbTheBestCarHire.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        lbTheBestCarHire.setForeground(new java.awt.Color(102, 0, 0));
        lbTheBestCarHire.setText("The Best ");

        lblMake.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lblMake.setText("Make");

        lblModel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lblModel.setText("Model");

        lblColour.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lblColour.setText("Colour");

        lblFuelType.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lblFuelType.setText("Fuel Type");

        lblNumberOfSeats.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lblNumberOfSeats.setText("Number of Seats");

        lstMake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstMake.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Audi", "BMW", "Ford", "Honda", "Lexus", "Mazda", "Mitsubishi", "Toyota", "Volkswagen" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstMake.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMake.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMakeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMake);

        lblTransmission.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lblTransmission.setText("Transmission");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        buttonGroupTransmission.add(rdAnyTransmission);
        rdAnyTransmission.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdAnyTransmission.setText("Any");

        buttonGroupTransmission.add(rdManual);
        rdManual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdManual.setText("Manual");

        buttonGroupTransmission.add(rdAutomatic);
        rdAutomatic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdAutomatic.setText("Automatic");

        jList2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Black", "Blue", "Silver", "Red", "White", "Pink", "Green" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        buttonGroupFuelType.add(rdAnyFuelType);
        rdAnyFuelType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdAnyFuelType.setText("Any");

        buttonGroupFuelType.add(rdPetrol);
        rdPetrol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdPetrol.setText("Petrol");
        rdPetrol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroupFuelType.add(rdDiesel);
        rdDiesel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdDiesel.setText("Diesel");

        buttonGroupFuelType.add(rdBioethanol);
        rdBioethanol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdBioethanol.setText("Bioethanol");

        buttonGroupFuelType.add(rdHybrid);
        rdHybrid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdHybrid.setText("Hybrid");

        buttonGroupNumberOfSeats.add(rd7seats);
        rd7seats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd7seats.setText("7");

        buttonGroupNumberOfSeats.add(rd2seats);
        rd2seats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd2seats.setText("2");

        buttonGroupNumberOfSeats.add(rd4seats);
        rd4seats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd4seats.setText("4");

        buttonGroupNumberOfSeats.add(rd5seats);
        rd5seats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd5seats.setText("5");

        buttonGroupNumberOfSeats.add(rd8seats);
        rd8seats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rd8seats.setText("8");

        jButton1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jButton1.setText("Place Order");

        jButton2.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jButton2.setText("Save to File");

        jButton3.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jButton3.setText("Load from File");

        jButton4.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jButton4.setText("Clear All");

        cmbModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Make" }));

        lbTheBestCarHire2.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        lbTheBestCarHire2.setForeground(new java.awt.Color(102, 0, 0));
        lbTheBestCarHire2.setText("Car Hire in Town!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTheBestCarHire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTheBestCarHire2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMake)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModel)
                                    .addComponent(lblTransmission)
                                    .addComponent(rdManual)
                                    .addComponent(rdAutomatic)
                                    .addComponent(rdAnyTransmission)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColour)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFuelType)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdAnyFuelType)
                                .addComponent(rdPetrol)
                                .addComponent(rdDiesel)
                                .addComponent(rdHybrid)
                                .addComponent(rdBioethanol)))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumberOfSeats)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rd4seats, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rd7seats, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rd5seats)
                                .addComponent(rd8seats, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rd2seats, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbTheBestCarHire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTheBestCarHire2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbImage)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblColour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMake)
                                    .addComponent(lblModel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(lblTransmission)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdAnyTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdManual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdAutomatic))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumberOfSeats)
                                .addGap(21, 21, 21)
                                .addComponent(rd2seats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rd4seats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rd5seats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rd7seats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rd8seats))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFuelType)
                                .addGap(18, 18, 18)
                                .addComponent(rdAnyFuelType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdPetrol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdDiesel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdHybrid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdBioethanol)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstMakeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMakeValueChanged
        //get the string selected in the lstMake
        String make = lstMake.getSelectedValue().toString();
        //adding items into a combo box
        //1. add each item into a Model : DefaultComboBoxModel
        //2. and when its done  assign the model to the combo box model : cmbModel.setModel(model);
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        switch (make) {
            case "Audi":
                model.addElement("Q2");
                model.addElement("Q5");
                model.addElement("A3");
                model.addElement("A5 Coupe");
                break;
            case "BMW":
                model.addElement("M Coupe");
                model.addElement("M2");
                model.addElement("M3");
                model.addElement("M4");
                model.addElement("M5");
                model.addElement("M6");
                break;
            case "Ford":
                model.addElement("C-MAX");
                model.addElement("CAPRI");
                model.addElement("FIESTA");
                model.addElement("FOCUS");
                model.addElement("GALAXY");
                model.addElement("KUGA");
                model.addElement("MONDEO");
                break;
            case "Honda":
                model.addElement("ACCORD");
                model.addElement("CIVIC");
                model.addElement("HR-V");
                model.addElement("CR-V");
                model.addElement("FIT");
                model.addElement("INTEDRA");
                break;
            case "Lexus":
                model.addElement("CT");
                model.addElement("GS");
                model.addElement("IS");
                model.addElement("RC F");
                model.addElement("RX");
                break;
            case "Mazda":
                model.addElement("121");
                model.addElement("323");
                model.addElement("CX-3");
                model.addElement("CX-5");
                model.addElement("MPV");
                break;
            case "Mitsubishi":
                model.addElement("CARISMA");
                model.addElement("COLT");
                model.addElement("LANCER");
                model.addElement("PAJERO");
                model.addElement("SPACE STAR");
                break;
            case "Toyota":
                model.addElement("AURIS");
                model.addElement("AVENSIS");
                model.addElement("COROLLA");
                model.addElement("COROLLA VERSO");
                model.addElement("PRIUS");
                model.addElement("YARIS");
                break;
            case "Volkswagen":
                model.addElement("BORA");
                model.addElement("CADDY");
                model.addElement("GOLF");
                model.addElement("JETTA");
                model.addElement("LUPO");
                model.addElement("PASSAT");
                model.addElement("POLO");
                model.addElement("SCIROCCO");
                model.addElement("TIGUAN");
                model.addElement("TAUREG");
                model.addElement("TOURAN");
                break;
            default:
                model.addElement("Choose Car Make");
        }
        cmbModel.setModel(model);// loads the model into cmbModel combo box
    }//GEN-LAST:event_lstMakeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaHire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFuelType;
    private javax.swing.ButtonGroup buttonGroupNumberOfSeats;
    private javax.swing.ButtonGroup buttonGroupTransmission;
    private javax.swing.JComboBox cmbModel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbTheBestCarHire;
    private javax.swing.JLabel lbTheBestCarHire2;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblFuelType;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNumberOfSeats;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JList lstMake;
    private javax.swing.JRadioButton rd2seats;
    private javax.swing.JRadioButton rd4seats;
    private javax.swing.JRadioButton rd5seats;
    private javax.swing.JRadioButton rd7seats;
    private javax.swing.JRadioButton rd8seats;
    private javax.swing.JRadioButton rdAnyFuelType;
    private javax.swing.JRadioButton rdAnyTransmission;
    private javax.swing.JRadioButton rdAutomatic;
    private javax.swing.JRadioButton rdBioethanol;
    private javax.swing.JRadioButton rdDiesel;
    private javax.swing.JRadioButton rdHybrid;
    private javax.swing.JRadioButton rdManual;
    private javax.swing.JRadioButton rdPetrol;
    // End of variables declaration//GEN-END:variables
}
